{
  List<Throwable> errors=getTasksErrors();
  if (!errors.isEmpty()) {
    StringBuilder message=new StringBuilder(1024);
    message.append("There are expected no exceptions during the test, but ").append(errors.size()).append(" raised:");
    for (    Throwable throwable : errors) {
      String stacktrace=Throwables.getStackTraceAsString(throwable);
      message.append('\n').append(stacktrace);
    }
    Assert.fail(message.toString());
  }
}
