{
  exception=new DuplicateParamException();
  assertNotNull(exception);
  NamedParamsExceptionTest.assertMessage("null",exception);
  exception=new DuplicateParamException("message");
  NamedParamsExceptionTest.assertMessage("message",exception);
  Throwable t=mock(Throwable.class);
  when(t.getStackTrace()).thenReturn(new StackTraceElement[0]);
  exception=new DuplicateParamException(t);
  assertEquals(t,exception.getCause());
  exception=new DuplicateParamException("message",t);
  NamedParamsExceptionTest.assertMessage("message",exception);
  assertEquals(t,exception.getCause());
}
