{
  try {
    execute();
    endProcessing("end");
  }
 catch (  KettleException je) {
    System.out.println("A serious error occurred!" + Const.CR + je.getMessage());
  }
}
