{
  RuntimeException runtimeException=new RuntimeException("Exception handle");
  when(selectedTrashFileItemsMock.toArray()).thenReturn(new TrashBrowseController.UIDeletedObject[]{uiDirectoryObjectMock});
  when(selectedTrashFileItemsMock.size()).thenReturn(1);
  doReturn(uiDirectoryObjectMock).when(selectedTrashFileItemsMock).get(0);
  doThrow(runtimeException).when(trashServiceMock).undelete(anyList());
  doReturn(true).when(mainControllerMock).handleLostRepository(any(Throwable.class));
  trBrController.undelete();
  verify(messageBoxMock,never()).setTitle("Error");
  verify(messageBoxMock,never()).setAcceptLabel("OK");
  verify(messageBoxMock,never()).setMessage(contains("Exception handle"));
  verify(messageBoxMock,never()).open();
  verify(deckMock,never()).setSelectedIndex(1);
}
