{
  try {
    throw new IdNotFoundException(message,objectName,pathToObject,objectType);
  }
 catch (  IdNotFoundException testedException) {
    assertTrue(testedException.getMessage().contains(message));
    assertEquals(null,testedException.getCause());
    assertEquals(objectName,testedException.getObjectName());
    assertEquals(pathToObject,testedException.getPathToObject());
    assertEquals(objectType,testedException.getObjectType());
  }
}
