{
  try {
    return Math.round(value);
  }
 catch (  Exception e) {
    return -1;
  }
}
