{
  try {
    result=job.execute(entryNr + 1,result);
  }
 catch (  KettleJobException e) {
    log.logError(toString(),"An error occurred executing this job entry : " + e.getMessage());
    result.setNrErrors(1);
  }
  finished=true;
}
