{
  assertProperties(properties);
  try {
    properties.walk(handler);
  }
 catch (  FunctorException e) {
    throw (KettleException)e.getCause();
  }
}
