{
  try {
    return tryNext();
  }
 catch (  Exception e) {
    handler.error(e);
    return null;
  }
}
