{
  exception=new NamedParamsException();
  assertNotNull(exception);
  assertMessage("null",exception);
  exception=new NamedParamsException("message");
  assertMessage("message",exception);
  Throwable t=mock(Throwable.class);
  when(t.getStackTrace()).thenReturn(new StackTraceElement[0]);
  exception=new NamedParamsException(t);
  assertEquals(t,exception.getCause());
  exception=new NamedParamsException("message",t);
  assertMessage("message",exception);
  assertEquals(t,exception.getCause());
}
