{
  try {
    logBasic(Messages.getString("Flattener.Log.StartingToRun"));
    while (processRow(meta,data) && !isStopped())     ;
  }
 catch (  Exception e) {
    logError(Messages.getString("Flattener.Log.UnexpectedErrorIn") + debug + "' : "+ e.toString());
    logError(Const.getStackTracker(e));
    setErrors(1);
    stopAll();
  }
 finally {
    dispose(meta,data);
    logSummary();
    markStop();
  }
}
